### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by zaverichintan** [mix-and-match/mix-and-match-tutorial#1]
Hello,
Thanks for the paper and proposing new metrics. Could you please share the code for the model and the evaluation metrics? 

Thanks in advance. 
Regards, 
Chintan Zaveri

**Comment by sadegh-aa** [comment]
Hi Chintan,

Thanks for your interest. We have plans to release the full source code for the human motion prediction, which will contain the evaluation metrics.
Sorry for the delay.

**Comment by zaverichintan** [comment]
Hello @sadegh-aa,
When will the code be released? 
Kindly let me know the tentative date for the release?

**Comment by mix-and-match** [comment]
Thanks for your enquiry. Unfortunately, due to IP issues (partially related to Data61's fund), we've been unable to release the code as planned. I will update the code in this repo after resolving the IP issues.
